"""
api.py — REST API for BhashaRAG, so a separately-built frontend (e.g. one
generated with Antigravity) can talk to this backend over HTTP instead of
using the built-in Gradio UI (app.py).

Run with (from the project folder):
    python src/api.py

Interactive API docs (auto-generated by FastAPI) will be at:
    http://localhost:8000/docs
"""
import os
import shutil
import uuid
from typing import List, Optional

from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

import ingest
import retrieve
from retrieve import dense_search, bm25_search, reciprocal_rank_fusion, rerank
from query_expansion import expand_query
from llm import generate_answer
from tts import synthesize_speech
from config import TOP_K_RERANKED, BASE_DIR

# Absolute paths so the API works no matter which folder it is started from.
PDF_DIR = os.path.join(BASE_DIR, "data", "pdfs")
AUDIO_DIR = os.path.join(BASE_DIR, "data", "audio")
os.makedirs(PDF_DIR, exist_ok=True)
os.makedirs(AUDIO_DIR, exist_ok=True)

app = FastAPI(title="BhashaRAG API", version="1.0")

# Allow a locally-hosted frontend (any origin, any port) to call this API.
# Tighten this to your actual frontend URL before deploying publicly.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serve generated audio files at /audio/<filename>
app.mount("/audio", StaticFiles(directory=AUDIO_DIR), name="audio")


# ---------- request / response schemas ----------

class QueryRequest(BaseModel):
    question: str
    use_expansion: bool = True
    use_reranker: bool = True
    voice: bool = False
    voice_lang: str = "hi-IN"


class SourceRef(BaseModel):
    document: str
    page: int


class QueryResponse(BaseModel):
    answer: str
    sources: List[SourceRef]
    audio_url: Optional[str] = None


class IndexResponse(BaseModel):
    status: str
    files_indexed: int


# ---------- endpoints ----------

@app.get("/api/health")
def health():
    return {"status": "ok"}


@app.post("/api/upload")
async def upload_pdfs(files: List[UploadFile] = File(...)):
    """Upload one or more PDFs. Does NOT index them yet — call /api/index after."""
    saved = []
    for f in files:
        if not f.filename.lower().endswith(".pdf"):
            raise HTTPException(400, f"'{f.filename}' is not a PDF.")
        dest = os.path.join(PDF_DIR, f.filename)
        with open(dest, "wb") as out:
            shutil.copyfileobj(f.file, out)
        saved.append(f.filename)
    return {"status": "uploaded", "files": saved}


@app.post("/api/index", response_model=IndexResponse)
def index_documents(reset: bool = True):
    """Parse, chunk, embed, and index every PDF currently in data/pdfs/."""
    pdf_count = len([f for f in os.listdir(PDF_DIR) if f.lower().endswith(".pdf")])
    if pdf_count == 0:
        raise HTTPException(400, "No PDFs found. Upload some via /api/upload first.")
    try:
        ingest.ingest_pdfs(PDF_DIR, reset=reset, model=retrieve._load_embedding_model())
    except Exception as e:
        raise HTTPException(500, f"Indexing failed: {e}")
    retrieve.reload_indexes()   # make queries see the fresh index
    return IndexResponse(status="indexed", files_indexed=pdf_count)


@app.post("/api/query", response_model=QueryResponse)
def query(req: QueryRequest):
    """Ask a question. Returns a grounded answer, its sources, and optionally spoken audio."""
    if not req.question.strip():
        raise HTTPException(400, "Question cannot be empty.")

    variants = expand_query(req.question) if req.use_expansion else [req.question]

    all_hits, seen_ids = [], set()
    try:
        for variant in variants:
            dense_hits = dense_search(variant)
            bm25_hits = bm25_search(variant)
            fused = reciprocal_rank_fusion([dense_hits, bm25_hits])
            for hit in fused:
                if hit["id"] not in seen_ids:
                    seen_ids.add(hit["id"])
                    all_hits.append(hit)
    except FileNotFoundError:
        raise HTTPException(404, "No indexed documents to search. Upload and index PDFs first.")

    top_chunks = (
        rerank(req.question, all_hits, top_k=TOP_K_RERANKED)
        if req.use_reranker else all_hits[:TOP_K_RERANKED]
    )

    if not top_chunks:
        raise HTTPException(404, "No indexed documents to search. Upload and index PDFs first.")

    try:
        answer = generate_answer(req.question, top_chunks)
    except Exception as e:  # e.g. bad/missing Gemini key, free-tier rate limit
        raise HTTPException(502, f"The language model request failed: {e}")

    sources = [
        SourceRef(document=c["metadata"]["source"], page=c["metadata"]["page"])
        for c in top_chunks
    ]
    # de-duplicate sources while preserving order
    seen_src = set()
    unique_sources = []
    for s in sources:
        key = (s.document, s.page)
        if key not in seen_src:
            seen_src.add(key)
            unique_sources.append(s)

    audio_url = None
    if req.voice:
        filename = f"{uuid.uuid4().hex}.wav"
        output_path = os.path.join(AUDIO_DIR, filename)
        result_path = synthesize_speech(answer, language_code=req.voice_lang, output_path=output_path)
        if result_path:
            audio_url = f"/audio/{filename}"

    return QueryResponse(answer=answer, sources=unique_sources, audio_url=audio_url)


@app.get("/api/documents")
def list_documents():
    """List currently uploaded/indexed PDF filenames."""
    files = [f for f in os.listdir(PDF_DIR) if f.lower().endswith(".pdf")]
    return {"documents": files}


if __name__ == "__main__":
    import uvicorn

    port = int(os.environ.get("PORT", 10000))

    uvicorn.run(
        app,
        host="0.0.0.0",
        port=port
    )